---
- hosts: webservers
  become: true
  roles:
    - setup_docker
    - deploy_jenkins_container
    - deploy_git
    - deploy_terraform
    - install_kubectl
      #- deploy_docker_app
      #- deploy_jenkins_on_host

